
var TestVariable : int = 1

var TestVariable : int = 12

var Test : float = 12

print not (23.2 / 2.0 >= 23.2 / 3.0); print "TT"
print "This is a test"


Test = 12

block {




    print Test
}


block {print Test;}
block{print Test}; print HI

OnBegin()
OnBegin() : void = {
    Print("Hi there {Name}")
}


OnBegin(Test : int, Test2 : int) : void = {
    Print("Hi there {Name}")
}

OnBegin(Test, Test2)